### PR TITLE
various changes

### PR DESCRIPTION
**Pull request by a-dekker**
- Added landscape support
- Notification now using nemomobile notifications
- Changed phone control to device control
- Compatible with/optimised for jolla tablet
- Harbourized (passes all harbour tests)

### CODE REVIEW

**Comment by almindor** [comment]
Can you please re-do this as either two pull requests or just one without the harbourization?

I have a "harbour" branch for the store version that already has the names harbourized.

**Comment by a-dekker** [comment]
I noticed you had a harbour branch. Is there a reason you want to keep a harbourized and non-harbourized version? My assumption was you where in a transition to a harbourized version, so I also included that.

**Comment by almindor** [comment]
Yeah I keep both because I also released on non-harbour shops (like openrepos). I always work on the non-harbour version and then merge into harbour because usually the changes in code don't touch the renamed files.

Translations are a bit of a PITA tho so I might stop supporting non-harbour at some point.

**Comment by a-dekker** [comment]
Almost everyone uses the harbour prefix also in openrepos, as it makes it more simple.
I will create new pull requests later. Thanks for the swift responses so far.

**Comment by almindor** [comment]
I'll try to merge harbour into master this week so you can re-submit into a single branch. Should've done that ages ago but there was always something else to do.

**Pull request closed without merging**
